### ISSUE TITLE
Liaison with CEDIA

### ISSUE THREAD

**Issue by intmarine** [SMPTE/ag-10#26]
A Liaison between SMPTE and CEDIA (Custom Electronic Design and Installation Association, an ANSI accredited standards organization) was created 4 or 5 years ago with signed documents from the SVP SMPTE and CEDIA Director of Technology. 
The SMPTE 27C P-member Shawn Nagelli is the Rapporteur from SMPTE <snageli@m.smpte.org>
The CEDIA Senior Director of Technology & Standards Walt Zerbe <wzerbe@cedia.org> is the contact for CEDIA.

Any questions to cflynn@m.smpte.org

**Comment by SteveLLamb** [comment]
@sh-smpte @SMPTE/svp can you confirm the paperwork is ok to add this to our list?
