### ISSUE TITLE
Need link for AG-10c

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/ag-10#8]
Need link to add for bibliography or AG-10c.

**Comment by fschleich** [comment]
AG-10c is private, how about:

`AG-10c - Individual Contact Information (private document, updated continuously)`

**Comment by SteveLLamb** [comment]
Cool, yes I like that. Thanks!

Added this in [39344b0](https://github.com/SMPTE/ag-10/commit/39344b09a4d74775d02a42db80f6e28a702300f4), will close when PR closes.

**Comment by SteveLLamb** [comment]
This got missed when refreshing the tooling updates, added back into new PR.
